// autogenerated by ServerDbGenerator
#pragma warning disable IDE1006 // Naming Styles
#pragma warning disable IDE0017 // Object Initialization
#pragma warning disable IDE0028 // Collection Initialization
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
#pragma warning disable CS0105 // Using directive appeared previously in this namespace
#pragma warning disable CS0612 // Type or member is obsolete
using crosscutting.sql;
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using crosscutting.cqrs;
namespace transactions.sql
{
	using transactions.sql;
	using Z.EntityFramework.Plus;
// generated class, do not modify, source here: file:///placeholder
public partial class txnTransactionsDBContext : EntityDbContext<txnTransactionsDBContext>
{
	// top-level queries with composites
	public IQueryable<txnInventoryItemDbEntity> InventoryItemsWithComposites =>
		InventoryItems
			.Include(c => c.EndReference).ThenInclude(c => c.Date)
			.Include(c => c.EndReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.EndReference).ThenInclude(c => c.Text)
			.Include(c => c.Identity)
			.Include(c => c.Receipent).ThenInclude(c => c.Date)
			.Include(c => c.Receipent).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.Receipent).ThenInclude(c => c.Text)
			.Include(c => c.References).ThenInclude(c => c.Date)
			.Include(c => c.References).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.References).ThenInclude(c => c.Text)
			.Include(c => c.StartReference).ThenInclude(c => c.Date)
			.Include(c => c.StartReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.StartReference).ThenInclude(c => c.Text)
		;
	public IQueryable<txnContainerDbEntity> ContainersWithComposites =>
		Containers
			.Include(c => c.EndReference).ThenInclude(c => c.Date)
			.Include(c => c.EndReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.EndReference).ThenInclude(c => c.Text)
			.Include(c => c.Identity)
			.Include(c => c.Receipent).ThenInclude(c => c.Date)
			.Include(c => c.Receipent).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.Receipent).ThenInclude(c => c.Text)
			.Include(c => c.References).ThenInclude(c => c.Date)
			.Include(c => c.References).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.References).ThenInclude(c => c.Text)
			.Include(c => c.StartReference).ThenInclude(c => c.Date)
			.Include(c => c.StartReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.StartReference).ThenInclude(c => c.Text)
		;
	public IQueryable<txnShippingUnitDbEntity> ShippingUnitsWithComposites =>
		ShippingUnits
			.Include(c => c.EndReference).ThenInclude(c => c.Date)
			.Include(c => c.EndReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.EndReference).ThenInclude(c => c.Text)
			.Include(c => c.Identity)
			.Include(c => c.Receipent).ThenInclude(c => c.Date)
			.Include(c => c.Receipent).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.Receipent).ThenInclude(c => c.Text)
			.Include(c => c.References).ThenInclude(c => c.Date)
			.Include(c => c.References).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.References).ThenInclude(c => c.Text)
			.Include(c => c.StartReference).ThenInclude(c => c.Date)
			.Include(c => c.StartReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.StartReference).ThenInclude(c => c.Text)
		;

		public IQueryable<txnShippingUnitDbEntity> ShippingUnitsWithCompositesAsSplitQuery =>
			ShippingUnits
				.Include(c => c.EndReference).ThenInclude(c => c.Date)
				.Include(c => c.EndReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
				.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
				.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
				.Include(c => c.EndReference).ThenInclude(c => c.Text)
				.Include(c => c.Identity)
				.Include(c => c.Receipent).ThenInclude(c => c.Date)
				.Include(c => c.Receipent).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
				.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
				.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
				.Include(c => c.Receipent).ThenInclude(c => c.Text)
				.Include(c => c.References).ThenInclude(c => c.Date)
				.Include(c => c.References).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
				.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
				.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
				.Include(c => c.References).ThenInclude(c => c.Text)
				.Include(c => c.StartReference).ThenInclude(c => c.Date)
				.Include(c => c.StartReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
				.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
				.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
				.Include(c => c.StartReference).ThenInclude(c => c.Text)
				.AsSplitQuery()
			;

		public IQueryable<txnShippingUnitDbEntity> ShippingUnitsWithCompositesAsSplitQuery1 =>
			ShippingUnits
				.Include(c => c.EndReference).ThenInclude(c => c.Date)
				.Include(c => c.EndReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
				.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
				.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
				.Include(c => c.EndReference).ThenInclude(c => c.Text)
				.Include(c => c.Identity)
				.Include(c => c.Receipent).ThenInclude(c => c.Date)
				.Include(c => c.Receipent).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
				.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
				.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
				.Include(c => c.Receipent).ThenInclude(c => c.Text)
				.Include(c => c.References).ThenInclude(c => c.Date)
				.Include(c => c.References).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
				.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
				.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
				.Include(c => c.References).ThenInclude(c => c.Text)
				.Include(c => c.StartReference).ThenInclude(c => c.Date)
				.Include(c => c.StartReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
				.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
				.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
				.Include(c => c.StartReference).ThenInclude(c => c.Text)
				.AsSplitQuery()
			;

		public IQueryable<txnShippingUnitDbEntity> ShippingUnitsWithCompositesOptimized =>
			ShippingUnits
				.IncludeOptimized(c => c.EndReference)
				.IncludeOptimized(c => c.EndReference.Date)
				.IncludeOptimized(c => c.EndReference.Entity)
				.IncludeOptimized(c => c.EndReference.Entity.Summary)
				.IncludeOptimized(c => c.EndReference.Location)
				.IncludeOptimized(c => c.EndReference.Location.Spatial)
				.IncludeOptimized(c => c.EndReference.Location.Spatial.Geographies)
				.IncludeOptimized(c => c.EndReference.Location.Spatial.Geometry)
				.IncludeOptimized(c => c.EndReference.Text)
				.IncludeOptimized(c => c.Identity)
				.IncludeOptimized(c => c.Receipent)
				.IncludeOptimized(c => c.Receipent.Date)
				.IncludeOptimized(c => c.Receipent.Entity)
				.IncludeOptimized(c => c.Receipent.Entity.Summary)
				.IncludeOptimized(c => c.Receipent.Location)
				.IncludeOptimized(c => c.Receipent.Location.Spatial)
				.IncludeOptimized(c => c.Receipent.Location.Spatial.Geographies)
				.IncludeOptimized(c => c.Receipent.Location.Spatial.Geometry)
				.IncludeOptimized(c => c.Receipent.Text)
				.IncludeOptimized(c => c.References)
				.IncludeOptimized(c => c.References.Select(c0 => c0.Date))
				.IncludeOptimized(c => c.References.Select(c0 => c0.Entity))
				.IncludeOptimized(c => c.References.Select(c0 => c0.Entity.Summary))
				.IncludeOptimized(c => c.References.Select(c0 => c0.Location))
				.IncludeOptimized(c => c.References.Select(c0 => c0.Location.Spatial))
				.IncludeOptimized(c => c.References.Select(c0 => c0.Location.Spatial.Geographies))
				.IncludeOptimized(c => c.References.Select(c0 => c0.Location.Spatial.Geometry))
				.IncludeOptimized(c => c.References.Select(c0 => c0.Text))
				.IncludeOptimized(c => c.StartReference)
				.IncludeOptimized(c => c.StartReference.Date)
				.IncludeOptimized(c => c.StartReference.Entity)
				.IncludeOptimized(c => c.StartReference.Entity.Summary)
				.IncludeOptimized(c => c.StartReference.Location)
				.IncludeOptimized(c => c.StartReference.Location.Spatial)
				.IncludeOptimized(c => c.StartReference.Location.Spatial.Geographies)
				.IncludeOptimized(c => c.StartReference.Location.Spatial.Geometry)
				.IncludeOptimized(c => c.StartReference.Text)
			;

		public IQueryable<txnSUPathwayDistributionDbEntity> SUPathwayDistributionsWithComposites =>
		SUPathwayDistributions
			.Include(c => c.Items)
		;
	public IQueryable<txnShippingActivityDbEntity> ShippingActivitiesWithComposites =>
		ShippingActivities
			.Include(c => c.Types).ThenInclude(c => c.Items)
		;
	public IQueryable<txnTaskDbEntity> TasksWithComposites =>
		Tasks
			.Include(c => c.EndReference).ThenInclude(c => c.Date)
			.Include(c => c.EndReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.EndReference).ThenInclude(c => c.Text)
			.Include(c => c.Identity)
			.Include(c => c.Receipent).ThenInclude(c => c.Date)
			.Include(c => c.Receipent).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.Receipent).ThenInclude(c => c.Text)
			.Include(c => c.References).ThenInclude(c => c.Date)
			.Include(c => c.References).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.References).ThenInclude(c => c.Text)
			.Include(c => c.StartReference).ThenInclude(c => c.Date)
			.Include(c => c.StartReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.StartReference).ThenInclude(c => c.Text)
		;
	public IQueryable<txnConsignmentDbEntity> ConsignmentsWithComposites =>
		Consignments
			.Include(c => c.EndReference).ThenInclude(c => c.Date)
			.Include(c => c.EndReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.EndReference).ThenInclude(c => c.Text)
			.Include(c => c.Identity)
			.Include(c => c.Receipent).ThenInclude(c => c.Date)
			.Include(c => c.Receipent).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.Receipent).ThenInclude(c => c.Text)
			.Include(c => c.References).ThenInclude(c => c.Date)
			.Include(c => c.References).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.References).ThenInclude(c => c.Text)
			.Include(c => c.StartReference).ThenInclude(c => c.Date)
			.Include(c => c.StartReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.StartReference).ThenInclude(c => c.Text)
		;
	public IQueryable<txnRevisionCounterDbEntity> RevisionCountersWithComposites =>
		RevisionCounters
		;
	public IQueryable<txnCargoReportDbRecord> CargoReportsWithComposites =>
		CargoReports
		;
	public IQueryable<txnSAPFeedbackItemDbRecord> SAPFeedbackItemsWithComposites =>
		SAPFeedbackItems
		;
	public IQueryable<txnCargoRequestDbEntity> CargoRequestsWithComposites =>
		CargoRequests
			.Include(c => c.EndReference).ThenInclude(c => c.Date)
			.Include(c => c.EndReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.EndReference).ThenInclude(c => c.Text)
			.Include(c => c.Identity)
			.Include(c => c.Receipent).ThenInclude(c => c.Date)
			.Include(c => c.Receipent).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.Receipent).ThenInclude(c => c.Text)
			.Include(c => c.References).ThenInclude(c => c.Date)
			.Include(c => c.References).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.References).ThenInclude(c => c.Text)
			.Include(c => c.StartReference).ThenInclude(c => c.Date)
			.Include(c => c.StartReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.StartReference).ThenInclude(c => c.Text)
		;
	public IQueryable<txnWorkItemDbEntity> WorkItemsWithComposites =>
		WorkItems
			.Include(c => c.EndReference).ThenInclude(c => c.Date)
			.Include(c => c.EndReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.EndReference).ThenInclude(c => c.Text)
			.Include(c => c.Identity)
			.Include(c => c.Receipent).ThenInclude(c => c.Date)
			.Include(c => c.Receipent).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.Receipent).ThenInclude(c => c.Text)
			.Include(c => c.References).ThenInclude(c => c.Date)
			.Include(c => c.References).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.References).ThenInclude(c => c.Text)
			.Include(c => c.StartReference).ThenInclude(c => c.Date)
			.Include(c => c.StartReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.StartReference).ThenInclude(c => c.Text)
		;
	public IQueryable<txnWorkOrderDbEntity> WorkOrdersWithComposites =>
		WorkOrders
			.Include(c => c.EndReference).ThenInclude(c => c.Date)
			.Include(c => c.EndReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.EndReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.EndReference).ThenInclude(c => c.Text)
			.Include(c => c.Identity)
			.Include(c => c.Receipent).ThenInclude(c => c.Date)
			.Include(c => c.Receipent).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.Receipent).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.Receipent).ThenInclude(c => c.Text)
			.Include(c => c.References).ThenInclude(c => c.Date)
			.Include(c => c.References).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.References).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.References).ThenInclude(c => c.Text)
			.Include(c => c.StartReference).ThenInclude(c => c.Date)
			.Include(c => c.StartReference).ThenInclude(c => c.Entity).ThenInclude(c => c.Summary)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geographies)
			.Include(c => c.StartReference).ThenInclude(c => c.Location).ThenInclude(c => c.Spatial).ThenInclude(c => c.Geometry)
			.Include(c => c.StartReference).ThenInclude(c => c.Text)
		;
}
}
#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS0105 // Using directive appeared previously in this namespace
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
#pragma warning restore IDE0028 // Collection Initialization
#pragma warning restore IDE0017 // Object Initialization
#pragma warning restore IDE1006 // Naming Styles
