// autogenerated by ServerDbGenerator
#pragma warning disable IDE1006 // Naming Styles
#pragma warning disable IDE0017 // Object Initialization
#pragma warning disable IDE0028 // Collection Initialization
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
#pragma warning disable CS0105 // Using directive appeared previously in this namespace
#pragma warning disable CS0612 // Type or member is obsolete
using crosscutting.sql;
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using crosscutting.cqrs;
namespace transactions.sql
{
	using transactions.sql;
// generated class, do not modify, source here: file:///placeholder
public partial class txnTransactionsDBContext : EntityDbContext<txnTransactionsDBContext>
{
	public static string SchemaName => "txn";
	public txnTransactionsDBContext(Guid platformId, DbContextOptions<txnTransactionsDBContext> options) : base(platformId, options) { OnContextCreated(options); }
	public DbSet<txnAuthIdentityDbEntity> AuthIdentities { get; set; }
	public DbSet<txnReferenceDbEntity> References { get; set; }
	public DbSet<txnEntitySummaryReferenceDbEntity> EntitySummaryReferences { get; set; }
	public DbSet<txnEntitySummaryDbEntity> EntitySummaries { get; set; }
	public DbSet<txnGeoLocationReferenceDbEntity> GeoLocationReferences { get; set; }
	public DbSet<txnSpatialDbEntity> Spatials { get; set; }
	public DbSet<txnSpatialGeometryDbEntity> SpatialGeometries { get; set; }
	public DbSet<txnSpatialGeographyDbEntity> SpatialGeographies { get; set; }
	public DbSet<txnTextReferenceDbEntity> TextReferences { get; set; }
	public DbSet<txnDateReferenceDbEntity> DateReferences { get; set; }
	public DbSet<txnSUPathwayDistributionItemDbEntity> SUPathwayDistributionItems { get; set; }
	public DbSet<txnShippingActivityTypeDbEntity> ShippingActivityTypes { get; set; }
	public DbSet<txnShippingActivityItemDbEntity> ShippingActivityItems { get; set; }
	public DbSet<txnInventoryItemDbEntity> InventoryItems { get; set; }
	public DbSet<txnContainerDbEntity> Containers { get; set; }
	public DbSet<txnShippingUnitDbEntity> ShippingUnits { get; set; }
	public DbSet<txnSUPathwayDistributionDbEntity> SUPathwayDistributions { get; set; }
	public DbSet<txnShippingActivityDbEntity> ShippingActivities { get; set; }
	public DbSet<txnTaskDbEntity> Tasks { get; set; }
	public DbSet<txnConsignmentDbEntity> Consignments { get; set; }
	public DbSet<txnRevisionCounterDbEntity> RevisionCounters { get; set; }
	public DbSet<txnCargoReportDbRecord> CargoReports { get; set; }
	public DbSet<txnSAPFeedbackItemDbRecord> SAPFeedbackItems { get; set; }
	public DbSet<txnCargoRequestDbEntity> CargoRequests { get; set; }
	public DbSet<txnWorkItemDbEntity> WorkItems { get; set; }
	public DbSet<txnWorkOrderDbEntity> WorkOrders { get; set; }
}
}
#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS0105 // Using directive appeared previously in this namespace
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
#pragma warning restore IDE0028 // Collection Initialization
#pragma warning restore IDE0017 // Object Initialization
#pragma warning restore IDE1006 // Naming Styles
